contracts_folder: hyperdrive_solidity/contracts

plugins:
  - name: etherscan
  - name: solidity
  - name: foundry
  - name: alchemy

dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.8.1
  - name: Aave
    github: aave/aave-v3-core
    version: 1.17.2
  - name: Mocks
    local: hyperdrive_solidity/test/
    contracts_folder: src/contracts

solidity:
  import_remapping:
    - "@openzeppelin/contracts=OpenZeppelin/4.8.1"
    - "openzeppelin-contracts/contracts=OpenZeppelin/4.8.1"
    - "@aave=Aave/1.17.2"
    - "forge-std=../../lib/forge-std/src"

ethereum:
  default_network: local
  local:
    default_provider: foundry
  goerli:
    required_confirmations: 1

foundry:
  port: 8555
  anvil:
    timestamp: 0
    block_base_fee_per_gas: 0
    code_size_limit: 0
    disable_block_gas_limit: True
  # gas-limit <GAS_LIMIT>         The block gas limit
  # gas-price <GAS_PRICE>         The gas price

test:
  number_of_accounts: 5
