contracts_folder: hyperdrive_solidity/contracts

plugins:
  - name: notebook
  - name: etherscan
  - name: solidity
  - name: foundry

dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.8.1

solidity:
  import_remapping:
    - "@openzeppelin/contracts=OpenZeppelin/4.8.1"

ethereum:
  default_network: local
  local:
    default_provider: foundry

foundry:
  port: 8555
