# ### Python Image ###
FROM python:3.9.16-bullseye

# set bash as default shell
SHELL ["/bin/bash", "-c"]

WORKDIR /app

# copy requirements and setup files
COPY requirements* ./
COPY ape-config.yaml.example ./ape-config.yaml

# install base dependencies
RUN python -m pip install --upgrade pip
RUN python -m pip install .[with-dependencies, docs]
RUN ape plugins install .
