title = "example simulation config"

[market]
target_liquidity = {type="uniform", low=1e6, high=10e6} # in shares
vault_age = {type="uniform", low=0, high=1} # fraction of a year
vault_apr = {type = "constant", value = 0.05} # decimal
base_asset_price = 1  # aka market price

[amm]
pricing_model_name = "Hyperdrive" # specify a pricing model
pool_apr = {type="uniform", low=0.02, high=0.9} # decimal
trade_fee_percent = {type="uniform", low=0.1, high=0.5} # decimal
redemption_fee_percent = {type="uniform", low=0.1, high=0.5} # decimal
floor_fee = 0  # minimum fee percentage (bps)

[simulator]
num_trading_days = 180  # should be <= pool_duration
num_blocks_per_day = 7200 # 24 * 60 * 60 / 12 = 12 second block time
num_position_days = 90 # time lapse between token mint and expiry as days
agent_policies = ["single_long"] # specify a list of trading policies by name
shuffle_users = true # shuffle order of action (as if random gas paid)
init_lp = true # use initial LP to seed pool
compound_vault_apr = true # whether or not to use compounding revenue for the underlying yield source
precision = 64 # 64 is max precision (and the default for numpy)
random_seed = 123 # to be passed to a rng
logging_level = "info" # must be one of [DEBUG, INFO, WARNING, ERROR, CRITICAL]
