name: build and upload wheels

on:
  push:
    tags:
      - "v*"

jobs:
  build-wheels-linux:
    name: build linux wheel
    runs-on: ubuntu-latest
    steps:
      - name: checkout agent0
        uses: actions/checkout@v4
        with:
          token: ${{github.token}}

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          token: ${{github.token}}

      - name: set up pip
        run: python -m pip install --upgrade pip

      - name: build agent0
        shell: bash
        run: source scripts/build_wheels.sh

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-linux
          path: dist/*.whl

  build-sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-sdist
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build-wheels-linux, build-sdist]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Download wheel artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true
      - name: Upload to pypi
        uses: pypa/gh-action-pypi-publish@release/v1

  generate-dependencies:
    needs: [upload_pypi]
    name: generate dependency file
    runs-on: ubuntu-latest
    steps:
      - name: checkout agent0
        uses: actions/checkout@v4
        with:
          token: ${{github.token}}

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          token: ${{github.token}}

      - name: generate dependency file
        shell: bash
        run: source scripts/generate_deps.sh

      - name: upload dependency file
        uses: actions/upload-artifact@v4
        with:
          name: frozen-requirements
          path: ./frozen-requirements.txt

  upload-dependencies:
    needs: [generate-dependencies]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download dependency list artifact
        uses: actions/download-artifact@v4
        with:
          pattern: frozen-requirements.txt
          path: ./
      - name: Upload dependency list to release
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          gh release upload ${{ github.ref_name }} ./frozen-requirements.txt
