name: clear_notebooks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
