name: "Docker: Build and push elf-simulations image"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    tags: ["*"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/elf-simulations

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check GitHub rate limit at start
        uses: wakamex/rate-limit-action@master
        with:
          token: ${{ secrets.GH_GITHUB_COM_TOKEN}}

      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_GITHUB_COM_TOKEN}}

      - name: Log in to the Container registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_GITHUB_COM_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.5.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # Add a version tag when a valid semver tag is pushed.
            type=semver,pattern={{version}}
            # Add the edge tag to every image to represent the latest commit to main
            type=edge,branch=main

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.0
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Check GitHub rate limit at end
        uses: wakamex/rate-limit-action@master
        with:
          token: ${{ secrets.GH_GITHUB_COM_TOKEN}}
