name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check GitHub rate limit at start
        uses: wakamex/rate-limit-action@master
        with:
          token: ${{ secrets.GH_GITHUB_COM_TOKEN || github.token }}

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_GITHUB_COM_TOKEN || github.token }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          token: ${{ secrets.GH_GITHUB_COM_TOKEN || github.token }}
      - run: |
          python -m pip install --upgrade pip
          python -m pip install .[with-dependencies,ape]

      - name: Ensure clear Jupyter Notebooks
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1

      - name: Run black
        run: python -m black --check --diff .

      - name: Run pylint
        run: |
          pylint --rcfile=.pylintrc $(git diff --name-only origin/main...HEAD | grep '.py$')

      - name: Check GitHub rate limit at end
        uses: wakamex/rate-limit-action@master
        with:
          token: ${{ secrets.GH_GITHUB_COM_TOKEN || github.token}}
