name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check GitHub rate limit at start
        run: |
          curl -sI -H "Authorization: token ${{ secrets.GH_GITHUB_COM_TOKEN }}" https://api.github.com/rate_limit | grep X-Ratelimit-Remaining

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_GITHUB_COM_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          token: ${{ secrets.GH_GITHUB_COM_TOKEN }}
      - run: |
          python -m pip install --upgrade pip
          python -m pip install .[with-dependencies]
          ape plugins install .

      - name: Ensure clear Jupyter Notebooks
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1

      - name: Run black
        run: python -m black --check --diff .

      - name: Run pylint
        run: python -m pylint $(git ls-files '*.py')

      - name: Check GitHub rate limit at end
        run: |
          curl -sI -H "Authorization: token ${{ secrets.GH_GITHUB_COM_TOKEN }}" https://api.github.com/rate_limit | grep X-Ratelimit-Remaining
