name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black~=22.0 pylint
          python -m pip install stochastic --ignore-requires-python
          python -m pip install -r requirements-${{ matrix.python-version }}.txt
      - name: Analyzing code with black
        run: python -m black --check --diff .
      - name: Analysing code with pylint
        run: python -m pylint $(git ls-files '*.py')
      - name: Ensure clear Jupyter Notebooks
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
    paths-ignore:
      - examples/everlasting_bots.py
