name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{github.token}}

      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: setup foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          token: ${{github.token}}

      - name: upgrade pip
        run: python -m pip install --upgrade pip

      - name: check out hyperdrive
        uses: actions/checkout@master
        with:
          repository: delvtech/hyperdrive
          path: "./hyperdrive"
          ssh-key: ${{ secrets.HYPERDRIVE_ACCESS_KEY }}

      - name: check out pyperdrive
        uses: actions/checkout@master
        with:
          repository: delvtech/pyperdrive
          path: "./pyperdrive"
          ssh-key: ${{ secrets.PYPERDRIVE_ACCESS_KEY }}

      - name: build pyperdrive
        shell: bash
        run: source scripts/build_pyperdrive.sh

      - name: install requirements
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt

      - name: ensure clear Jupyter Notebooks
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1

      - name: run black
        run: python -m black --check --diff .

      - name: get all Python files
        id: list_files
        run: |
          echo "files=$(git ls-files '*.py' '*.pyi' | xargs)" >> $GITHUB_OUTPUT

      - name: run Pylint on files
        run: |
          files="${{ steps.list_files.outputs.files }}"
          if [ -n "$files" ]; then
            pylint --rcfile=.pylintrc $files
          else
            echo "No Python files found."
          fi
