name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/delvtech/elf-simulations/elf-simulations:testing
    steps:
      - name: Check GitHub rate limit at start
        uses: wakamex/rate-limit-action@master
        with:
          token: ${{ secrets.GH_GITHUB_COM_TOKEN || github.token }}

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_GITHUB_COM_TOKEN || github.token }}
          fetch-depth: 0  # Fetches all history for all branches and tags.

      - name: Mark safe directory
        run: |
          git config --global --add safe.directory /__w/elf-simulations/elf-simulations

      - name: Fetch base commit
        run: |
          git fetch origin ${{ github.event.pull_request.base.sha }}

      - name: Get changed Python files
        id: changed_files
        run: |
          echo "files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '.py$' | grep -v 'disabled_tests/' | xargs)" >> $GITHUB_ENV

      - name: Ensure clear Jupyter Notebooks
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1

      - name: Run black
        run: python -m black --check --diff .

      - name: Run Pylint on changed files
        run: |
          files="${{ steps.changed_files.outputs.files }}"
          if [ -n "$files" ]; then
            pylint --rcfile=.pylintrc $files
          else
            echo "No Python files have changed."
          fi

      - name: Check GitHub rate limit at end
        uses: wakamex/rate-limit-action@master
        with:
          token: ${{ secrets.GH_GITHUB_COM_TOKEN || github.token}}
