name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/delvtech/elf-simulations/elf-simulations:edge
    steps:
      - name: Check GitHub rate limit at start
        uses: wakamex/rate-limit-action@master
        with:
          token: ${{ secrets.GH_GITHUB_COM_TOKEN || github.token }}

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_GITHUB_COM_TOKEN || github.token }}
          fetch-depth: 2

      - name: Ensure clear Jupyter Notebooks
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1

      - name: Run black
        run: python -m black --check --diff .

      - name: Debug git state
        run: |
          git log --oneline -n 2
          git status

      - name: Get changed Python files
        id: changed_files
        run: |
          echo "files=$(git diff --name-only origin/${{ github.base_ref }} HEAD | grep '.py$' | xargs)" >> $GITHUB_OUTPUT

      - name: Run Pylint on changed files
        run: |
          files="${{ steps.changed_files.outputs.files }}"
          if [ -n "$files" ]; then
            pylint --rcfile=.pylintrc $files
          else
            echo "No Python files have changed."
          fi

      - name: Check GitHub rate limit at end
        uses: wakamex/rate-limit-action@master
        with:
          token: ${{ secrets.GH_GITHUB_COM_TOKEN || github.token}}
