name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{github.token}}

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          token: ${{github.token}}

      - name: upgrade pip
        run: python -m pip install --upgrade pip

      - name: install requirements
        run: |
          python -m pip install --upgrade -r requirements.txt
          python -m pip install --upgrade -r requirements-rl.txt
          python -m pip install --upgrade -r requirements-dev.txt

      - name: run black
        run: python -m black --config pyproject.toml --check --diff .

      - name: get all Python files
        id: list_files
        run: |
          echo "files=$(git ls-files '*.py' '*.pyi' | xargs)" >> $GITHUB_OUTPUT

      - name: run Pylint on files
        run: |
          files="${{ steps.list_files.outputs.files }}"
          if [ -n "$files" ]; then
            pylint --rcfile=.pylintrc $files
          else
            echo "No Python files found."
          fi
