name: static

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: static
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/delvtech/elf-simulations/elf-simulations:testing
    steps:
      - name: Check GitHub rate limit at start
        uses: wakamex/rate-limit-action@master
        with:
          token: ${{ secrets.GH_GITHUB_COM_TOKEN || github.token}}

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_GITHUB_COM_TOKEN || github.token }}

      - name: Mark safe directory
        run: |
          git config --global --add safe.directory /__w/elf-simulations/elf-simulations

      - name: Pyright
        run: |
          files=$(git ls-files '*.py' | grep -v 'disabled_tests/')
          python -m pyright $files

      - name: Check GitHub rate limit at end
        uses: wakamex/rate-limit-action@master
        with:
          token: ${{ secrets.GH_GITHUB_COM_TOKEN || github.token}}
