name: static

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: static
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{github.token}}

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          token: ${{github.token}}

      - name: install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: install requirements
        run: |
          uv venv .venv -p 3.10
          source .venv/bin/activate
          uv pip install --upgrade agent0[all] @ .
          uv pip install --upgrade -r requirements-hyperdrivepy.txt 

      - name: analysing code with pyright
        run: |
          source .venv/bin/activate
          python -m pyright $(git ls-files '*.py' '*.pyi')
