name: static

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: static
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-${{ matrix.python-version }}.txt
          python -m pip install . # Install the elfpy module
      - name: Analysing code with pyright
        run: python -m pyright .
