name: static

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: static
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install python dependencies
        run: |
          python -m pip install stochastic --ignore-requires-python
          python -m pip install -r requirements.txt
          ape plugins install .
          python -m pip install .

      - name: Analysing code with pyright
        run: python -m pyright $(git ls-files '*.py')
