name: static

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: static
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_GITHUB_COM_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          token: ${{ secrets.GH_GITHUB_COM_TOKEN }}
      - run: |
          python -m pip install --upgrade pip
          python -m pip install .[with-dependencies]
          ape plugins install .

      - name: Analysing code with pyright
        run: python -m pyright $(git ls-files '*.py')
