name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: install packages
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # if needed

      - name: install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.11 # install deps in 1m33s (231fa89628bd781756e2194eceea8192c8e62410)
          # python-version: 3.10.10 # install deps in 1m46s (4f328ed1624fae3a15531c8c4b7394fb865b2d21)
          # python-version: 3.10.9 # install deps in 1m32s (9fa485884eadae5f0ad025b649f9d0c8120c8f19)

      - name: Install python dependencies
        run: |
          python -m pip install stochastic --ignore-requires-python
          python -m pip install -r requirements.txt
          ape plugins install .
          python -m pip install .
          python -m pip install coverage

      - name: Run pytest with coverage
        run: |
          coverage run -m pytest

      - name: Generate coverage report
        run: |
          coverage xml -i report -m
          coverage xml -i html

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          flags: unittests
          fail_ci_if_error: true
