name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/delvtech/elf-simulations/elf-simulations:testing
    steps:
      - name: Check GitHub rate limit at start
        uses: wakamex/rate-limit-action@master
        with:
          token: ${{ secrets.GH_GITHUB_COM_TOKEN || github.token}}

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_GITHUB_COM_TOKEN || github.token}}

      - name: Mark safe directory
        run: |
          git config --global --add safe.directory /__w/elf-simulations/elf-simulations

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: install packages
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
        env:
          # A warning is thrown here unnecessarily.  tracking issue here:
          # https://github.com/github/vscode-github-actions/issues/222
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # if needed

      - name: install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run pytest with coverage
        run: |
          coverage run -m pytest --ignore=tests/cross_platform

      - name: Generate coverage report
        run: |
          coverage xml -i
          coverage html -i

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: unittests
          fail_ci_if_error: true
          # A warning is thrown here unnecessarily.  tracking issue here:
          # https://github.com/github/vscode-github-actions/issues/222
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Check GitHub rate limit at end
        uses: wakamex/rate-limit-action@master
        with:
          token: ${{ secrets.GH_GITHUB_COM_TOKEN || github.token}}
