name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{github.token}}

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: install packages
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
        env:
          # A warning is thrown here unnecessarily.  tracking issue here:
          # https://github.com/github/vscode-github-actions/issues/222
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # if needed

      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: setup foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          token: ${{github.token}}

      - name: check out hyperdrive
        uses: actions/checkout@master
        with:
          repository: delvtech/hyperdrive
          path: "./hyperdrive"
          ssh-key: ${{ secrets.HYPERDRIVE_ACCESS_KEY }}

      - name: check out pyperdrive
        uses: actions/checkout@master
        with:
          repository: delvtech/pyperdrive
          path: "./pyperdrive"
          ssh-key: ${{ secrets.PYPERDRIVE_ACCESS_KEY }}

      - name: upgrade pip
        run: python -m pip install --upgrade pip

      - name: build pyperdrive
        shell: bash
        run: source scripts/build_pyperdrive.sh

      - name: install requirements
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt

      - name: run pytest with coverage
        run: |
          coverage run -m pytest

      - name: generate coverage report
        run: |
          coverage xml -i
          coverage html -i

      - name: upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: unittests
          fail_ci_if_error: true
          # A warning is thrown here unnecessarily.  tracking issue here:
          # https://github.com/github/vscode-github-actions/issues/222
          token: ${{ secrets.CODECOV_TOKEN }}
