name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black~=22.0 pylint pytest nose
          python -m pip install stochastic --ignore-requires-python
          python -m pip install -r requirements-${{ matrix.python-version }}.txt
          python -m pip install .
          python -m pip install coverage
      - name: Run pytest with coverage
        run: |
          coverage run -m pytest
      - name: Generate coverage report
        run: |
          coverage xml -i report -m
          coverage xml -i html
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          flags: unittests
          fail_ci_if_error: true
